%prefix "lsys"

%auxil "ParserStr *"
%value "ParseData *"

%header {
    #include "../lsystem.h"
    #include "lsys_parse_util.h"

    LRuleset parse_string_to_ruleset(char * in, unsigned int max_rules);
 
}

%source {
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#define PCC_GETCHAR(auxil) parser_str_getch(auxil)

#define PCC_ERROR(auxil) err_out(auxil)
void err_out(ParserStr * auxil){
    auxil->error.error_text = calloc(32, sizeof(char));
    snprintf(auxil->error.error_text, 32, "Syntax Error at %d", auxil->pos);
    auxil->error.has_errored = true;
    return;
}
/*
static const char *dbg_str[] = { "Evaluating rule", "Matched rule", "Abandoning rule" };
 define PCC_DEBUG(auxil, event, rule, level, pos, buffer, length) \
    fprintf(stderr, "%*s%s %s @%zu [%.*s]\n", (int)((level) * 2), "", dbg_str[event], rule, pos, (int)(length), buffer)
}*/

}

lrule <- (n:name _ ':')? _ (lc:context _ '<')? _ p:letter_with_binding _ ('>' _ rc:context)? _ (':' _ q:boolterm)? _ '->' _ res:result _ EOL? { $$ = mk_pd_rule(n, lc, p, rc, q, res, true); }

name <- < [A-Za-z0-9_]+ > { $$ = mk_parse_data(PARSE_DATA_string); $$->string_val = strdup($1); $$->list_length = 1;}

context <- l:context r:letter_with_binding {$$ = pd_node_append(l,r,true); }
         / l:letter_with_binding { $$ = l; }

letter_with_binding <- < [\x22-\x27\x2a-\x39\x3e-\x7e\x3b] > ('(' _ b:bindinglist _ ')')? { $$ = mk_pd_ruleword( *$1, b, true ); }

bindinglist <- bl:bindinglist _ ',' _ b:binding? {$$ = pd_node_append(bl,b,true);}
             / b:binding { $$ = b; }

binding <- l:letter { $$ = l; }

result <- l:result _ r:letter_with_term  { $$ = pd_node_append(l,r,true); }
        / l:letter_with_term { $$ = l; }

letter_with_term <- < [\x22-\x27\x2a-\x39\x3e-\x7e\x3b] > ('(' _ t:termlist _ ')')? { $$ = mk_pd_resultword( *$1, t, true); }

termlist <- l:termlist _ ',' _ r:term { $$ = pd_node_append(l, r, true); }  
         / t:term { $$ = t; }

boolterm <- l:boolterm _ '&' _ r:boolfact { $$ = mk_node_and(l, r, true); }
          / l:boolterm _ '|' _ r:boolfact { $$ = mk_node_and(l, r, true); }
          / '!' _ x:boolfact { $$ = mk_node_not(x, true); }
          / b:boolfact { $$ = b; }

boolfact <- l:term _ '=' _ r:term { $$ = mk_node_eq(l, r, true); }
          / l:term _ '>' _ r:term { $$ = mk_node_gt(l, r, true); }
          / l:term _ '<' _ r:term { $$ = mk_node_lt(l, r, true); }
          / l:term _ '>=' _ r:term { $$ = mk_node_geq(l, r, true); }
          / l:term _ '<=' _ r:term { $$ = mk_node_leq(l, r, true); }
          / l:term _ '!=' _ r:term { $$ = mk_node_neq(l, r, true); }
          / b:boolprim {$$ = b; }

boolprim <- b:boolean { $$ = b; }
          / '(' _ b:boolterm _ ')' { $$ = b; }

term <- l:term _ '+' _ r:factor { $$ = mk_node_binplus(l, r, true); }
      / l:term _ '-' _ r:factor { $$ = mk_node_binminus(l, r, true); }
      / e:factor                { $$ = e; }

factor <- l:factor _ '*' _ r:unary { $$ = mk_node_multiply(l, r, true); }
        / l:factor _ '/' _ r:unary { $$ = mk_node_divide(l, r, true); }
        / e:unary                  { $$ = e; }

unary <- '+' _ e:unary { $$ = mk_node_uplus(e, true); }
       / '-' _ e:unary { $$ = mk_node_uminus(e, true); }
       / e:primary     { $$ = e; }

primary <- d:dbl { $$ = d; }
         / '(' _ t:term _ ')' { $$ = t; }
         / l:letter { $$ = l; }

dbl <- < [+-]?[0-9]+([.][0-9]+)? > { $$ = mk_node_dbl_lit(strtod($1, NULL)); } 

boolean <- 'true' { $$ = mk_node_bool_lit(true); }
      / 'false' { $$ = mk_node_bool_lit(false); }

letter <- < [a-z] > { $$ = mk_node_letter_lit(*$1); }

_      <- [ \t]*

EOL    <- '\n' / '\r\n' / '\r' / ';'

EOF    <- 'EOF'.* / '\0' / '\0x03' / '\0x04'

%%

LRuleset parse_string_to_ruleset(char * in, unsigned int max_rules){
    if (max_rules <= 0) return (LRuleset){0, NULL};
    ParserStr * aux = mk_parser_str(in);
    ParseData * res;
    ParseData * out = malloc(sizeof(ParseData) * max_rules);
    memset(out, '\0', sizeof(ParseData) * max_rules);
    lsys_context_t *ctx = lsys_create(aux);
    int idx = -1;
    while (lsys_parse(ctx, &res)){
        if (idx < ((int)max_rules) -1){
            idx++;
            if (aux->error.has_errored) break;
            out[idx] = *res;
        } 
    }
    lsys_destroy(ctx);
    if (aux->error.has_errored) {
        printf("Error: %s", aux->error.error_text);
        free(out);
        return (LRuleset){0, NULL};
    }
    LRuleset result = (LRuleset){ .num_rules = 0, .rules = NULL};
    result.num_rules = idx+1;
    result.rules = malloc(sizeof(LRule) * (idx+1));
    for (unsigned int i = 0; i <= idx; i++){
        result.rules[i] = *(out[i].lrule_val);
    }
    free(out);
    return result;
}
