%prefix "lsys"

%auxil "ParserStr *"
%value "ParseData *"

%header {
    #include "lsystem2.h"
    #include "lsys_parse_util.h"
}

%source {
#include <stdio.h>
#include <string.h>
#define PCC_GETCHAR(auxil) parser_str_getch(auxil)
}

result <- r:ruleset _ EOF { $$ = r; }

ruleset <- l:ruleset _ r:lrule _ EOL {$$ = pd_node_append(l,r,true); }
         / r:lrule _ EOL { $$ = r; }

lrule <- (n:name _ ':')? _ (lc:context _ '<')? _ p:letter_with_binding _ ('>' _ rc:context)? _ (':' _ q:boolterm)? _ '->' _ res:result { $$ = mk_pd_rule(n, lc, p, rc, q, res, true); }

name <- < [A-Za-z0-9_]+ > { $$ = mk_parse_data(PARSE_DATA_string); $$->string_val = strdup($1); $$->list_length = 1;}

context <- l:context _ r:letter_with_binding {$$ = pd_node_append(l,r,true); }
         / l:letter_with_binding { $$ = l; }

letter_with_binding <- < [A-Za-z0-9] > ('(' _ b:bindinglist _ ')')? { $$ = mk_pd_ruleword( *$1, b, true ); }

bindinglist <- bl:bindinglist _ ',' _ b:binding? {$$ = pd_node_append(bl,b,true);}
             / b:binding { $$ = b; }

binding <- l:letter { $$ = l; }

result <- l:result _ r:letter_with_term  { $$ = pd_node_append(l,r,true); }
        / l:letter_with_term { $$ = l; }

letter_with_term <- < [A-Za-z] > ('(' _ t:termlist _ ')')? { $$ = mk_pd_resultword( *$1, t, true); }

termlist <- l:termlist _ ',' _ r:term { $$ = pd_node_append(l, r, true); }  
         / t:term { $$ = t; }

boolterm <- l:boolterm _ '&' _ r:boolfact { $$ = mk_node_and(l, r, true); }
          / l:boolterm _ '|' _ r:boolfact { $$ = mk_node_and(l, r, true); }
          / '!' _ x:boolfact { $$ = mk_node_not(x, true); }
          / b:boolfact { $$ = b; }

boolfact <- l:term _ '=' _ r:term { $$ = mk_node_eq(l, r, true); }
          / l:term _ '>' _ r:term { $$ = mk_node_gt(l, r, true); }
          / l:term _ '<' _ r:term { $$ = mk_node_lt(l, r, true); }
          / l:term _ '>=' _ r:term { $$ = mk_node_geq(l, r, true); }
          / l:term _ '<=' _ r:term { $$ = mk_node_leq(l, r, true); }
          / l:term _ '!=' _ r:term { $$ = mk_node_neq(l, r, true); }
          / b:boolprim {$$ = b; }

boolprim <- b:boolean { $$ = b; }
          / '(' _ b:boolterm _ ')' { $$ = b; }

term <- l:term _ '+' _ r:factor { $$ = mk_node_binplus(l, r, true); }
      / l:term _ '-' _ r:factor { $$ = mk_node_binminus(l, r, true); }
      / e:factor                { $$ = e; }

factor <- l:factor _ '*' _ r:unary { $$ = mk_node_multiply(l, r, true); }
        / l:factor _ '/' _ r:unary { $$ = mk_node_divide(l, r, true); }
        / e:unary                  { $$ = e; }

unary <- '+' _ e:unary { $$ = mk_node_uplus(e, true); }
       / '-' _ e:unary { $$ = mk_node_uminus(e, true); }
       / e:primary     { $$ = e; }

primary <- d:dbl { $$ = d; }
         / '(' _ t:term _ ')' { $$ = t; }
         / l:letter { $$ = l; }

dbl <- < [+-]?[0-9]+([.][0-9]+)? > { $$ = mk_node_dbl_lit(strtod($1, NULL)); } 

boolean <- 'true' { $$ = mk_node_bool_lit(true); }
      / 'false' { $$ = mk_node_bool_lit(false); }

letter <- < [a-z] > { $$ = mk_node_letter_lit(*$1); }

_      <- [ \t]*

EOL    <- '\n' / '\r\n' / '\r' / ';'

EOF    <- 'EOF' / '\0' / '\0x03' / '\0x04'

%%
/*
ParseData * parse_string_to_ruleset(char * in){
    ParserStr * aux = mk_parser_str(in);
    ParseData * res;
    lsys_context_t *ctx = lsys_create(NULL);
    while (lsys_parse(ctx, &res)){
      printf("Parsed %d\n", res->list_length);
          print_pd(res ,"  ");
    }
    lsys_destroy(ctx);
    return res;
}*/

int main(){
    ParserStr * aux = mk_parser_str("F(j)G(k) -> FF \n a1 : F(G) -> U \n PP < F -> G \n EOF");
    ParseData * res;
    lsys_context_t *ctx = lsys_create(aux);
    while (lsys_parse(ctx, &res));
    lsys_destroy(ctx);
    return 0;
}
