%prefix "lsys"

%auxil "ParserStr *"
%value "ParseData *"

%header {
    #include "lsystem2.h"
}

%source {
#include <stdio.h>
#include <string.h>
#define PCC_GETCHAR(auxil) parser_str_getch(auxil)


}


lrule <- (n:name _ ':')? _ (lc:context _ '<')? _ p:premise _ ('>' _ rc:context)? _ (':' _ q:qualifier) _ '->' _ res:result _ EOL

name <- < [A-Za-z0-9_]+ > { $$ = create_parse_data(PARSE_DATA_string); $$->string_val = strdup($1);}

context <- c:letter_with_binding+

premise <- letter_with_binding

letter_with_binding <- < [A-Za-z0-9] > ('(' _ b:bindinglist _ ')')?

bindinglist <- bl:bindinglist ',' b:binding? 
            / binding

binding <- [a-z]

result <- letter_with_term+

letter_with_term <- < [A-Za-z0-9] > ('(' _ t:termlist _ ')')?

qualifier <- termlist

termlist <- l:termlist _ ',' _ r:term 

term <- l:term _ '+' _ r:factor { $$ = create_node( (LPayload){ .type=LPAYLOAD_binary_op_dbl, .binary_op_dbl_val = *lop_binary_plus} ); node_add_child($$, l); node_add_child($$, r); }
      / l:term _ '-' _ r:factor { $$ = create_node( (LPayload){ .type=LPAYLOAD_binary_op_dbl, .binary_op_dbl_val = *lop_binary_minus} ); node_add_child($$, l); node_add_child($$, r); }
      / e:factor                { $$ = e; }

factor <- l:factor _ '*' _ r:unary { $$ = create_node( (LPayload){ .type=LPAYLOAD_binary_op_dbl, .binary_op_dbl_val = *lop_multiply} ); node_add_child($$, l); node_add_child($$, r); }
        / l:factor _ '/' _ r:unary { $$ = create_node( (LPayload){ .type=LPAYLOAD_binary_op_dbl, .binary_op_dbl_val = *lop_divide} ); node_add_child($$, l); node_add_child($$, r); }
        / e:unary                  { $$ = e; }

unary <- '+' _ e:unary { $$ = create_node( (LPayload){ .type=LPAYLOAD_unary_op_dbl, .unary_op_dbl_val = *lop_unary_plus} ); node_add_child($$, e); }
       / '-' _ e:unary { $$ = create_node( (LPayload){ .type=LPAYLOAD_unary_op_dbl, .unary_op_dbl_val = *lop_unary_minus} ); node_add_child($$, e); }
       / e:primary     { $$ = e; }

primary <- < [0-9]+ >               { $$ = create_node( (LPayload){.type = LPAYLOAD_dbl, .dbl_val = strtod($1, NULL)} ); }
         / '(' _ e:expression _ ')' { $$ = e; }



_      <- [ \t]*

EOL    <- '\n' / '\r\n' / '\r' / ';'

%%

int main(){
    ParserStr * aux = mk_parser_str("1 + 24 * 3 * 4;");
    ParseData * res;
    lsys_context_t *ctx = lsys_create(aux);
    while (lsys_parse(ctx, &res)){
      print_LAst(res, "  ");
    }
    lsys_destroy(ctx);
    return 0;
}
