/* A packrat parser generated by PackCC 2.2.0 */

#ifndef PCC_INCLUDED_LSYSTEM_H
#define PCC_INCLUDED_LSYSTEM_H

#include "lsystem2.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct lsys_context_tag lsys_context_t;

lsys_context_t *lsys_create(ParserStr *auxil);
int lsys_parse(lsys_context_t *ctx, LAstNode **ret);
void lsys_destroy(lsys_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_LSYSTEM_H */
